[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "^3.13"
streamlit = "^1.40.2"
pandas = "^2.2.3"
plotly = "^5.24.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
